[versions]
agp = "8.12.3"
documentfile = "1.1.0"

[libraries]
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

